- name: Add flatpak remotes
  become: true
  community.general.flatpak_remote:
    name: "{{ item.name }}"
    state: present
    flatpakrepo_url: "{{ item.url }}"
  loop: "{{ flatpak_remotes }}"

- name: Add flatpaks
  become: true
  community.general.flatpak:
    name: "{{ item.package }}"
    state: present
    remote: "{{ item.remote }}"
  loop: "{{ flatpak_install }}"
