# SOURCE_TAG is the image version used (e.g. 41).
ARG SOURCE_TAG="41"
FROM quay.io/fedora-ostree-desktops/silverblue:${SOURCE_TAG}
# FROM quay.io/fedora/fedora-silverblue:${SOURCE_TAG}

COPY . /tmp/build/

## NOTES:
# - /var/lib/alternatives is required to prevent failure with some RPM installs
# - All RUN commands must end with ostree container commit:
#   https://coreos.github.io/rpm-ostree/container/#using-ostree-container-commit
RUN mkdir -p /var/lib/alternatives && \
    /tmp/build/build.sh && \
    rm -rf /tmp/build && \
    ostree container commit
