- name: Copy /usr content
  become: true
  ansible.builtin.copy:
    src: usr/
    dest: /usr/

- name: Copy config files
  become: true
  ansible.builtin.copy:
    src: etc/
    dest: /etc/

- name: Add executable permissions to scripts
  file:
    dest: "{{ item }}"
    mode: a+x
  loop:
    - /usr/lib/dnscrypt-proxy/enable
    - /usr/lib/dnscrypt-proxy/disable
