- name: Copy config files
  become: true
  ansible.builtin.copy:
    src: etc/
    dest: /etc/

- name: Symlink podman quadlet
  become: true
  file:
    path: /etc/containers/systemd/dnscrypt-proxy.container
    src: /etc/dnscrypt-proxy/dnscrypt-proxy.container
    state: link
