- hosts: all
  gather_facts: false
  tasks:
    - import_role:
        name: packages
    - import_role:
        name: squid
    - import_role:
        name: gnome
    - import_role:
        name: sudo
    - import_role:
        name: doh
    - import_role:
        name: system-update
