- name: Copy /usr content
  become: true
  ansible.builtin.copy:
    src: usr/
    dest: /usr/

- name: Copy config files
  become: true
  ansible.builtin.copy:
    src: etc/
    dest: /etc/

- name: Symlink config file
  become: true
  file:
    path: /etc/mitmproxy/config.yaml
    src: /etc/mitmproxy/vbox.yaml
    state: link
